export type Table = {
    id: number
    rowName: string
    description: string
    secondDescription?: string
    thirdDescription?: string
    fourthDescription?: string
    header?: string
    number?: string
    mainHeader?: string
    secondRowName?: string
    thirdRowName?: string
}

export const bpak: Table[] = [
    {
        id: 1,
        rowName: "Максимальна злітна маса",
        description: "33 кг",
        number: "01",
    },
    {
        id: 2,
        rowName: "Максимальна тривалість польоту",
        description: "40 хв без навантаження 25-30 хв з навантаженням",
        number: "02",
    },
    {
        id: 3,
        rowName: "Максимальна швидкість",
        description: "54 км/год 45 км/год",
        number: "03",
    },
    {
        id: 4,
        rowName: "Радіус дії радіоканалу управління",
        description: "до 15 км",
        number: "04",
    },
    {
        id: 5,
        rowName: "Максимальна висота польоту (AMSL)",
        description: "600 м",
        number: "05",
    },
    {
        id: 6,
        rowName: "Максимальна протяжність польоту",
        description: "до 10 км",
        number: "06",
    },
    {
        id: 7,
        rowName: "Максимально допустима швидкість вітру при старті",
        description: "10 м/с",
        number: "07",
    },
    {
        id: 8,
        rowName: "Корисне навантаження",
        description: "2 міни 82 мм, 4 міни 60 мм, 4 РКГ-3, 4 ПТАБ-2,5, 12 вогів 40-60 мм, 1 протитанкова міна",
        number: "08",
    },
    {
        id: 9,
        rowName: "Тепловізійна камера",
        description: "наявна",
        number: "09",
    },
    {
        id: 10,
        rowName: "Нічна камера",
        description: "наявна",
        number: "10",
    },
    {
        id: 11,
        rowName: "Гравітаційний приціл (показує прогнозоване попадіння снаряду)",
        description: "наявна",
        number: "11",
    },
    {
        id: 12,
        rowName: "Стійкість до РЕБ і РЕП засобів",
        description: "ППРЧ зв'язок, пройшов усі випробування в умовах РЕБ і дослідження РЕП",
        number: "12",
    },
    {
        id: 13,
        rowName: "Стійкість до завад навігації",
        description: "наявна",
        number: "13",
    },
    {
        id: 14,
        rowName: "Швидкозмінні скиди корисного навантаження",
        description: "наявна",
        number: "14",
    },
    {
        id: 15,
        rowName: "Виносна станція керування",
        description: "до 80 м",
        number: "15",
    }
]

export const fpv: Table[] = [
    {
    id: 1,
    rowName: "",
    description: "8”",
    secondDescription: "10”",
    header: "table-header"
    },
    {
    id: 2,
    rowName: "Максимальна дальність польоту",
    description: "до 13 км",
    secondDescription: "до 15 км",
    number: "01",
    },
    {
    id: 3,
    rowName: "Максимальна тривалість польоту з навантаженням",
    description: "13 хв",
    secondDescription: "15 хв",
    number: "02",
    },
    {
    id: 4,
    rowName: "Максимальна висота польоту",
    description: "500 м",
    secondDescription: "500 м",
    number: "03",
    },
    {
    id: 5,
    rowName: "Робоча висота польоту",
    description: "70 м",
    secondDescription: "70 м",
    number: "04",
    },
    {
    id: 6,
    rowName: "Крейсерська швидкість польоту БпАК",
    description: "60 км/год",
    secondDescription: "60 км/год",
    number: "05",
    },
    {
    id: 7,
    rowName: "Максимальна швидкість польоту БпАК",
    description: "100 км/год",
    secondDescription: "100 км/год",
    number: "06",
    },
    {
    id: 8,
    rowName: "Дальність виявлення та розпізнавання типових цілей (танк, автомобіль, ростова фігура) відеокамерою",
    description: "100 м",
    secondDescription: "100 м",
    number: "07",
    },
    {
    id: 9,
    rowName: "Середньоквадратичне відхилення від цілі",
    description: "1,5 м",
    secondDescription: "1,5 м",
    number: "08",
    },
    {
    id: 10,
    rowName: "Максимальна маса цільового навантаження",
    description: "до 1,5 кг",
    secondDescription: "до 2 кг",
    number: "09",
    },
    {
    id: 11,
    rowName: "Тип БпЛА",
    description: "коптерний",
    secondDescription: "коптерний",
    number: "10",
    },
    {
    id: 12,
    rowName: "Основне призначення",
    description: "ураження броньованої / не броньованої техніки, особового складу тощо",
    secondDescription: "ураження броньованої / не броньованої техніки, особового складу тощо",
    number: "11",
    },
    {
    id: 13,
    rowName: "Тип (марка) бойової частини",
    description: "термобарична, ОФ, кумулятивна, фугасна, тощо",
    secondDescription: "термобарична, ОФ, кумулятивна, фугасна, тощо",
    number: "12",
    },
    {
    id: 14,
    rowName: "Маса засобу ураження",
    description: "до 1,5 кг",
    secondDescription: "до 3 кг",
    number: "13",
    },
    {
    id: 15,
    rowName: "Спосіб захисту від неконтрольованого спрацювання бойової частини",
    description: "електричний та механічний",
    secondDescription: "електричний та механічний",
    number: "14",
    },
]
export const link: Table[] = [
    {
    id: 1,
    rowName: "Повна транспортна маса комплекту",
    description: "до 40 кг",
    number: "01",
    },
    {
    id: 2,
    rowName: "Транспортні габарити штативу у згорнутому стані",
    description: "висота - 1400 мм; ",
    number: "02",
    },
    {
    id: 3,
    rowName: "Транспортні габарити кейсу",
    description: "висота - 120 мм; довжина та ширина  - 350 мм",
    number: "03",
    },
    {
    id: 4,
    rowName: "Максимальна висота штативу",
    description: "до 8,5 м",
    number: "04",
    },
    {
    id: 5,
    rowName: "Тип живлення",
    description: "акумулятор 6s2p",
    number: "05",
    },
    {
    id: 6,
    rowName: "Час автономної роботи",
    description: "при використанні 6s тривалість роботи складатиме до 16 год*",
    number: "06",
    },
    {
    id: 7,
    rowName: "Стандартна довжина кабелю",
    description: "40 м",
    number: "07",
    },
    {
    id: 8,
    rowName: "Максимально допустима довжина кабелю",
    description: "до 80 м",
    number: "08",
    },
    {
    id: 9,
    rowName: "Діапазон напруг",
    description: "13.5 ... 30 V (АКБ 4s - 6s)",
    number: "09",
    },
    {
    id: 10,
    rowName: "Протоколи зв’язку на вибір:",
    description: "CRSF (S-PORT)",
    secondDescription: "модуль TBS CROSSFIRE / Happymodel Expresslrs / Sine.link",
    thirdDescription: "SBUS",
    fourthDescription: "модуль Sine.link",
    number: "10",
    },
    {
    id: 11,
    rowName: "Відеоприймач на вибір:",
    description: "Caddx 1.3 GHz VRX + Фільтр TBS 1.2 GHz VRX Notch Filter 868/915 MHz",
    secondDescription: "Частота: 1,3 ГГц; Кількість каналів: 9 (1060-1380 Мгц).",
    thirdDescription: "SKYZONE SteadyView X 5.8 Ghz",
    fourthDescription: "Частота: 5.8 ГГц; Кількість каналів: 48.",
    number: "11",
    },
]
export const battery: Table[] = [
    {
    id: 1,
    rowName: "",
    description: "4S2P",
    secondDescription: "6S1P",
    thirdDescription: "6S2P",
    fourthDescription: "6S3P",
    header: 'battery-table-header',
    },
    {
    id: 2,
    rowName: "Розміри",
    description: "145x45x45 мм",
    secondDescription: "75x65x45 мм",
    thirdDescription: "145x65x45 мм",
    fourthDescription: "215x65x45 мм",
    number: "01",
    },
    {
    id: 3,
    rowName: "Вага",
    description: "570 грам",
    secondDescription: "470 грам",
    thirdDescription: "850 грам",
    fourthDescription: "1250 грам",
    number: "02",
    },
    {
    id: 4,
    rowName: "Ємність акумулятора",
    description: "8400 мА/год",
    secondDescription: "4200 мА/год",
    thirdDescription: "8400 мА/год",
    fourthDescription: "12600 мА/год",
    number: "03",
    },
    {
    id: 5,
    rowName: "Номінальна напруга",
    description: "14,8 В",
    secondDescription: "22,2 В",
    thirdDescription: "22,2 В",
    fourthDescription: "22,2 В",
    number: "04",
    },
    {
    id: 6,
    rowName: "Мінімальна напруга",
    description: "10 В",
    secondDescription: "15 В",
    thirdDescription: "15 В",
    fourthDescription: "15 В",
    number: "05",
    },
    {
    id: 7,
    rowName: "Максимальна напруга",
    description: "16,8 В",
    secondDescription: "25,2 В",
    thirdDescription: "25,2 В",
    fourthDescription: "25,2 В",
    number: "06",
    },
    {
    id: 8,
    rowName: "Загальна ємність",
    description: "124 Вт/год",
    secondDescription: "93 Вт/год",
    thirdDescription: "186 Вт/год",
    fourthDescription: "280 Вт/год",
    number: "07",
    },
    {
    id: 9,
    rowName: "Струм віддачі",
    description: "90 А",
    secondDescription: "45 А",
    thirdDescription: "90 А",
    fourthDescription: "135 А",
    number: "08",
    },
    {
    id: 10,
    rowName: "Рекомендований струм зарядки",
    description: "8 А",
    secondDescription: "4 А",
    thirdDescription: "8 А",
    fourthDescription: "12 А",
    number: "09",
    },
    {
    id: 11,
    rowName: "Температуриний діапазон розряду",
    description: "-40С до +60С",
    secondDescription: "-40С до +60С",
    thirdDescription: "-40С до +60С",
    fourthDescription: "-40С до +60С",
    number: "10",
    },
    {
    id: 12,
    rowName: "Температуриний діапазон заряду",
    description: "0С до +45С",
    secondDescription: "0С до +45С",
    thirdDescription: "0С до +45С",
    fourthDescription: "0С до +45С",
    number: "11",
    },
]
export const sdsMini: Table[] = [
    {
    id: 1,
    rowName: "Вага",
    description: "270 г",
    number: "01",
    },
    {
    id: 2,
    rowName: "Матеріал",
    description: "Алюміній, ударостійкий полікарбонат",
    number: "02",
    },
    {
    id: 3,
    rowName: "Відстань від дрона до боєприпаса",
    description: "17 мм",
    number: "03",
    },
    {
    id: 4,
    rowName: "Виступ скида нижче дрона",
    description: "30 мм",
    number: "04",
    },
    {
    id: 5,
    rowName: "Діапазон діаметрів використовуваного вантажу",
    description: "від 42 мм до 82 мм",
    number: "05",
    },
    {
    id: 6,
    mainHeader: "Габарити системи скидання боєприпасів:",
    rowName: "Ширина",
    secondRowName: "Висота",
    thirdRowName: "Глибина",
    description: "140 мм",
    secondDescription: "69 мм",
    thirdDescription: "93 мм",
    number: "06",
    },
]